/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Waresa01;

import javax.swing.*;

/**
 *
 * @author sara
 */
public class Esencial02_i1 extends javax.swing.JFrame {

    /**
     * Creates new form Principal01
     */
    public Esencial02_i1() {
        this.setTitle("Presentación");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_base = new javax.swing.JPanel();
        pnl_izquierdo = new javax.swing.JPanel();
        lbl_nombre_i = new javax.swing.JLabel();
        txa_descripcion_i = new javax.swing.JTextArea();
        btn_home = new javax.swing.JButton();
        pnl_derecho = new javax.swing.JPanel();
        lbl_nombre_d = new javax.swing.JLabel();
        txa_descripcion_d = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(974, 546));

        pnl_base.setBackground(new java.awt.Color(90, 176, 233));

        lbl_nombre_i.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_nombre_i.setText("Presentación");

        txa_descripcion_i.setEditable(false);
        txa_descripcion_i.setColumns(20);
        txa_descripcion_i.setLineWrap(true);
        txa_descripcion_i.setRows(5);
        txa_descripcion_i.setText("Algunas palabras por parte de nuestro equipo.");
        txa_descripcion_i.setWrapStyleWord(true);

        btn_home.setText("Inicio");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_izquierdoLayout = new javax.swing.GroupLayout(pnl_izquierdo);
        pnl_izquierdo.setLayout(pnl_izquierdoLayout);
        pnl_izquierdoLayout.setHorizontalGroup(
            pnl_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_izquierdoLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnl_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_izquierdoLayout.createSequentialGroup()
                        .addComponent(btn_home)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_izquierdoLayout.createSequentialGroup()
                        .addComponent(txa_descripcion_i, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
            .addGroup(pnl_izquierdoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_nombre_i)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_izquierdoLayout.setVerticalGroup(
            pnl_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_izquierdoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbl_nombre_i)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txa_descripcion_i, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_home)
                .addGap(16, 16, 16))
        );

        lbl_nombre_d.setText("Proyecto Waresa");

        txa_descripcion_d.setEditable(false);
        txa_descripcion_d.setColumns(20);
        txa_descripcion_d.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txa_descripcion_d.setLineWrap(true);
        txa_descripcion_d.setRows(5);
        txa_descripcion_d.setText("Seguramente en algún momento de nuestras vidas hemos sentido el temor que surge al querer iniciar algo nuevo, al querer realizar algo desconocido y extraño, nos han surgido dudas que nos hacen cuestionar la realización de este proceso; por suerte, la mayoría de las veces 'lo más difícil es dar el primer paso', tener presente cómo iniciar adecuadamente y así saber que esperar eliminado de nuestro imaginario expectativas que pueden diferir mucho de la realidad y del resultado final.\n\nA través de Waresa Project se busca brindar esa guía y acompañamiento a dar el primer paso en el proceso de diseño y construcción de humedales artificiales.\n\nLos humedales artificiales son un sistema no convencional a través de la cual es posible obtener un porcentaje de depuración para aguas residuales. Este tipo de sistemas son implementados alrededor del mundo aproximadamente desde 3 décadas anteriores a la actual.  Estos sistemas basan su funcionamiento en los humedales naturales, ecosistemas conocidos como \"los riñones del planeta\" gracias a su capacidad depuradora. \n\nLa depuración de aguas residuales es un aspecto fundamental en el conjunto de factores ambientales y sanitarios para una comunidad, la realización de este procedimiento mediante soluciones alternativas beneficia en gran medida a las poblaciones rurales y poblaciones con baja densidad poblacional en las cuales la cobertura del sistema de alcantarillado es deficiente. Así mismo es implementado por diversos usuarios a manera de complemento del servicio de alcantarillado, buscando con ello un valor agregado en las aguas residuales que estos generan. \n\nEsperamos que esta herramienta sea de utilidad para nuestros usuarios y que les proporcione el acompañamiento adecuado en ese primer paso hacia la construcción de humedales artificiales. Les deseamos éxitos en este proceso y el victorioso cumplimiento de los objetivos planteados.\n\n");
        txa_descripcion_d.setWrapStyleWord(true);

        javax.swing.GroupLayout pnl_derechoLayout = new javax.swing.GroupLayout(pnl_derecho);
        pnl_derecho.setLayout(pnl_derechoLayout);
        pnl_derechoLayout.setHorizontalGroup(
            pnl_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_derechoLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(pnl_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_derechoLayout.createSequentialGroup()
                        .addComponent(lbl_nombre_d, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(556, 556, 556))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_derechoLayout.createSequentialGroup()
                        .addComponent(txa_descripcion_d, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );
        pnl_derechoLayout.setVerticalGroup(
            pnl_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_derechoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_nombre_d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txa_descripcion_d, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_baseLayout = new javax.swing.GroupLayout(pnl_base);
        pnl_base.setLayout(pnl_baseLayout);
        pnl_baseLayout.setHorizontalGroup(
            pnl_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_baseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_izquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_derecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_baseLayout.setVerticalGroup(
            pnl_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_baseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_derecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_izquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        Esencial02 es2 = new Esencial02();
        this.dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Esencial02_i1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Esencial02_i1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Esencial02_i1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Esencial02_i1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Esencial02_i1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home;
    private javax.swing.JLabel lbl_nombre_d;
    private javax.swing.JLabel lbl_nombre_i;
    private javax.swing.JPanel pnl_base;
    private javax.swing.JPanel pnl_derecho;
    private javax.swing.JPanel pnl_izquierdo;
    private javax.swing.JTextArea txa_descripcion_d;
    private javax.swing.JTextArea txa_descripcion_i;
    // End of variables declaration//GEN-END:variables
}
