package Waresa01;

import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author sara
 */
public class Esencial02_c1 extends javax.swing.JFrame {
    ImageIcon foto1, foto2, foto3, foto4, foto5, foto6;

    /**
     * Creates new form Principal01
     */
    public Esencial02_c1() {
        setVisible(true);
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        foto1=new ImageIcon(getClass().getResource("/WaresaRecursos/Poaceae.jpg"));
        lbl_imagen_c1.setIcon(new ImageIcon(foto1.getImage().getScaledInstance(lbl_imagen_c1.getWidth(),lbl_imagen_c1.getHeight(),Image.SCALE_DEFAULT)));
        foto2=new ImageIcon(getClass().getResource("/WaresaRecursos/Neotropical Typhaceae.jpeg"));
        lbl_imagen_c2.setIcon(new ImageIcon(foto2.getImage().getScaledInstance(lbl_imagen_c2.getWidth(),lbl_imagen_c2.getHeight(),Image.SCALE_DEFAULT)));
        foto3=new ImageIcon(getClass().getResource("/WaresaRecursos/Cyperus papyrus.jpeg"));
        lbl_imagen_c3.setIcon(new ImageIcon(foto3.getImage().getScaledInstance(lbl_imagen_c3.getWidth(),lbl_imagen_c3.getHeight(),Image.SCALE_DEFAULT)));


        foto4=new ImageIcon(getClass().getResource("/WaresaRecursos/Araceae.jpeg"));
        lbl_imagen_c4.setIcon(new ImageIcon(foto4.getImage().getScaledInstance(lbl_imagen_c4.getWidth(),lbl_imagen_c4.getHeight(),Image.SCALE_DEFAULT)));
        foto5=new ImageIcon(getClass().getResource("/WaresaRecursos/Canaceae.jpeg"));
        lbl_imagen_c5.setIcon(new ImageIcon(foto5.getImage().getScaledInstance(lbl_imagen_c5.getWidth(),lbl_imagen_c5.getHeight(),Image.SCALE_DEFAULT)));
        foto6=new ImageIcon(getClass().getResource("/WaresaRecursos/Cyperaceae.jpg"));
        lbl_imagen_c6.setIcon(new ImageIcon(foto6.getImage().getScaledInstance(lbl_imagen_c6.getWidth(),lbl_imagen_c6.getHeight(),Image.SCALE_DEFAULT)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl_base = new javax.swing.JPanel();
        pnl_izquierdo = new javax.swing.JPanel();
        lbl_icono_i = new javax.swing.JLabel();
        lbl_nombre_i1 = new javax.swing.JLabel();
        lbl_nombre_i2 = new javax.swing.JLabel();
        txa_descripcion_i = new javax.swing.JTextArea();
        btn_home = new javax.swing.JButton();
        scr_centro = new javax.swing.JScrollPane();
        pnl_centro = new javax.swing.JPanel();
        lbl_nombre_c1 = new javax.swing.JLabel();
        lbl_nombre_c2 = new javax.swing.JLabel();
        lbl_nombre_c3 = new javax.swing.JLabel();
        lbl_nombre_c3_1 = new javax.swing.JLabel();
        lbl_nombre_c3_2 = new javax.swing.JLabel();
        lbl_nombre_c4 = new javax.swing.JLabel();
        lbl_nombre_c5 = new javax.swing.JLabel();
        cbx_personas = new javax.swing.JComboBox<>();
        pnl_imagenes1 = new javax.swing.JPanel();
        lbl_imagen_c1 = new javax.swing.JLabel();
        lbl_imagen_c2 = new javax.swing.JLabel();
        lbl_imagen_c3 = new javax.swing.JLabel();
        cbx_imagen_c1 = new javax.swing.JCheckBox();
        cbx_imagen_c2 = new javax.swing.JCheckBox();
        cbx_imagen_c3 = new javax.swing.JCheckBox();
        pnl_imagenes2 = new javax.swing.JPanel();
        lbl_imagen_c4 = new javax.swing.JLabel();
        lbl_imagen_c5 = new javax.swing.JLabel();
        lbl_imagen_c6 = new javax.swing.JLabel();
        cbx_imagen_c4 = new javax.swing.JCheckBox();
        cbx_imagen_c5 = new javax.swing.JCheckBox();
        cbx_imagen_c6 = new javax.swing.JCheckBox();
        rbn_material_1 = new javax.swing.JRadioButton();
        rbn_material_2 = new javax.swing.JRadioButton();
        rbn_material_3 = new javax.swing.JRadioButton();
        txf_temperatura = new javax.swing.JTextField();
        pnl_derecho = new javax.swing.JPanel();
        lbl_nombre_d = new javax.swing.JLabel();
        lbl_nombre_d1 = new javax.swing.JLabel();
        lbl_nombre_d2 = new javax.swing.JLabel();
        lbl_nombre_d3 = new javax.swing.JLabel();
        lbl_nombre_d4 = new javax.swing.JLabel();
        lbl_nombre_d5 = new javax.swing.JLabel();
        lbl_resultadoCaudal = new javax.swing.JLabel();
        lbl_resultadoProfundidad = new javax.swing.JLabel();
        lbl_resultadoAreaSuperf = new javax.swing.JLabel();
        lbl_resultadoAncho = new javax.swing.JLabel();
        lbl_resultadoLargo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(974, 546));

        pnl_base.setBackground(new java.awt.Color(90, 176, 233));

        lbl_icono_i.setText("jLabel1");

        lbl_nombre_i1.setText("1. Componentes");

        lbl_nombre_i2.setText("del diseño");

        txa_descripcion_i.setEditable(false);
        txa_descripcion_i.setColumns(20);
        txa_descripcion_i.setRows(5);
        txa_descripcion_i.setText("El diseño de un humedal\nincluye el calculo de \ndiferentes componentes \npara lo cual se hace uso\nde leyes hidrológicas, \nmaatemáticas,\nse determinan áreas\nnecesarias entre otros \naspectos.\n\nIntroduzca los valores \nsolicictados para poder\nrealizar el cálulo de los \nvalores descritos con \nanterioridad el resumen \nde los resultados están \nen la sección continua\nal cálculo.");

        btn_home.setText("Inicio");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_izquierdoLayout = new javax.swing.GroupLayout(pnl_izquierdo);
        pnl_izquierdo.setLayout(pnl_izquierdoLayout);
        pnl_izquierdoLayout.setHorizontalGroup(
            pnl_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_izquierdoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_nombre_i1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_izquierdoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_nombre_i2)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_izquierdoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(txa_descripcion_i, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_izquierdoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_home)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_izquierdoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_icono_i)
                .addGap(63, 63, 63))
        );
        pnl_izquierdoLayout.setVerticalGroup(
            pnl_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_izquierdoLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lbl_icono_i)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(lbl_nombre_i1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(lbl_nombre_i2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txa_descripcion_i, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btn_home)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        lbl_nombre_c1.setText("Seleccione en cada aspecto:");

        lbl_nombre_c2.setText("1. Número de habitantes");

        lbl_nombre_c3.setText("2. Tipo de vegetación");

        lbl_nombre_c3_1.setText("Común");

        lbl_nombre_c3_2.setText("Ornamental");

        lbl_nombre_c4.setText("3. Material de relleno ");

        lbl_nombre_c5.setText("4. Temperatura del agua en °C");

        cbx_personas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", " " }));
        cbx_personas.setToolTipText("");
        cbx_personas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_personasActionPerformed(evt);
            }
        });

        lbl_imagen_c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WaresaRecursos/Canaceae.jpeg"))); // NOI18N
        lbl_imagen_c1.setText("1");

        lbl_imagen_c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WaresaRecursos/Canaceae.jpeg"))); // NOI18N
        lbl_imagen_c2.setText("1");

        lbl_imagen_c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WaresaRecursos/Canaceae.jpeg"))); // NOI18N
        lbl_imagen_c3.setText("1");

        cbx_imagen_c1.setText("Poaceae");

        cbx_imagen_c2.setText("Typhaceae");
        cbx_imagen_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_imagen_c2ActionPerformed(evt);
            }
        });

        cbx_imagen_c3.setText("Cyperaceae ");

        javax.swing.GroupLayout pnl_imagenes1Layout = new javax.swing.GroupLayout(pnl_imagenes1);
        pnl_imagenes1.setLayout(pnl_imagenes1Layout);
        pnl_imagenes1Layout.setHorizontalGroup(
            pnl_imagenes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_imagenes1Layout.createSequentialGroup()
                .addGroup(pnl_imagenes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_imagenes1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_imagen_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_imagenes1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(cbx_imagen_c1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_imagenes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_imagen_c2)
                    .addComponent(lbl_imagen_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_imagenes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_imagen_c3)
                    .addComponent(lbl_imagen_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_imagenes1Layout.setVerticalGroup(
            pnl_imagenes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_imagenes1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(pnl_imagenes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_imagen_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_imagen_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_imagen_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pnl_imagenes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_imagen_c1)
                    .addComponent(cbx_imagen_c2)
                    .addComponent(cbx_imagen_c3))
                .addContainerGap())
        );

        lbl_imagen_c4.setText("1");

        lbl_imagen_c5.setText("1");

        lbl_imagen_c6.setText("1");

        cbx_imagen_c4.setText("Araceae");

        cbx_imagen_c5.setText("Canaceae");
        cbx_imagen_c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_imagen_c5ActionPerformed(evt);
            }
        });

        cbx_imagen_c6.setText("Iridaceae");

        javax.swing.GroupLayout pnl_imagenes2Layout = new javax.swing.GroupLayout(pnl_imagenes2);
        pnl_imagenes2.setLayout(pnl_imagenes2Layout);
        pnl_imagenes2Layout.setHorizontalGroup(
            pnl_imagenes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_imagenes2Layout.createSequentialGroup()
                .addGroup(pnl_imagenes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_imagenes2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_imagen_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_imagenes2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(cbx_imagen_c4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_imagenes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_imagen_c5)
                    .addComponent(lbl_imagen_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_imagenes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_imagen_c6)
                    .addComponent(lbl_imagen_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_imagenes2Layout.setVerticalGroup(
            pnl_imagenes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_imagenes2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(pnl_imagenes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_imagen_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_imagen_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_imagen_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnl_imagenes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_imagen_c4)
                    .addComponent(cbx_imagen_c5)
                    .addComponent(cbx_imagen_c6))
                .addContainerGap())
        );

        buttonGroup1.add(rbn_material_1);
        rbn_material_1.setText("Arena Gruesa");
        rbn_material_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbn_material_1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbn_material_2);
        rbn_material_2.setText("Arena Gravosa");

        buttonGroup1.add(rbn_material_3);
        rbn_material_3.setText("Grava Fina");
        rbn_material_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbn_material_3ActionPerformed(evt);
            }
        });

        txf_temperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_temperaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_centroLayout = new javax.swing.GroupLayout(pnl_centro);
        pnl_centro.setLayout(pnl_centroLayout);
        pnl_centroLayout.setHorizontalGroup(
            pnl_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_centroLayout.createSequentialGroup()
                .addGroup(pnl_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_centroLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre_c3)
                            .addGroup(pnl_centroLayout.createSequentialGroup()
                                .addComponent(lbl_nombre_c2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbx_personas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_nombre_c3_1)))
                    .addGroup(pnl_centroLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_nombre_c5)
                                .addComponent(rbn_material_3)
                                .addComponent(rbn_material_2)
                                .addComponent(rbn_material_1)
                                .addComponent(lbl_nombre_c4)
                                .addComponent(txf_temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_nombre_c1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_centroLayout.createSequentialGroup()
                .addGroup(pnl_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_centroLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnl_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_imagenes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_imagenes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_centroLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lbl_nombre_c3_2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_centroLayout.setVerticalGroup(
            pnl_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_centroLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(lbl_nombre_c1)
                .addGap(18, 29, Short.MAX_VALUE)
                .addGroup(pnl_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre_c2)
                    .addComponent(cbx_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_nombre_c3)
                .addGap(18, 18, 18)
                .addComponent(lbl_nombre_c3_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_imagenes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl_nombre_c3_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_imagenes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl_nombre_c4)
                .addGap(18, 18, 18)
                .addComponent(rbn_material_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbn_material_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbn_material_3)
                .addGap(18, 18, 18)
                .addComponent(lbl_nombre_c5)
                .addGap(18, 18, 18)
                .addComponent(txf_temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        scr_centro.setViewportView(pnl_centro);

        lbl_nombre_d.setText("Resumen  de resultados");

        lbl_nombre_d1.setText("Caudal (m3/d)");

        lbl_nombre_d2.setText("Profundidad (m)");

        lbl_nombre_d3.setText("Área superficial (m2)");

        lbl_nombre_d4.setText("Ancho (m)");

        lbl_nombre_d5.setText("Largo (m)");

        lbl_resultadoCaudal.setText("jLabel1");

        lbl_resultadoProfundidad.setText("jLabel1");

        lbl_resultadoAreaSuperf.setText("jLabel1");

        lbl_resultadoAncho.setText("jLabel1");

        lbl_resultadoLargo.setText("jLabel1");

        javax.swing.GroupLayout pnl_derechoLayout = new javax.swing.GroupLayout(pnl_derecho);
        pnl_derecho.setLayout(pnl_derechoLayout);
        pnl_derechoLayout.setHorizontalGroup(
            pnl_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_derechoLayout.createSequentialGroup()
                .addGroup(pnl_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_derechoLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lbl_nombre_d1))
                    .addGroup(pnl_derechoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnl_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_nombre_d, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(lbl_resultadoCaudal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_resultadoProfundidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_resultadoAreaSuperf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_resultadoAncho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_resultadoLargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnl_derechoLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lbl_nombre_d2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_derechoLayout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addGroup(pnl_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_derechoLayout.createSequentialGroup()
                        .addComponent(lbl_nombre_d3)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_derechoLayout.createSequentialGroup()
                        .addComponent(lbl_nombre_d4)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_derechoLayout.createSequentialGroup()
                        .addComponent(lbl_nombre_d5)
                        .addGap(75, 75, 75))))
        );
        pnl_derechoLayout.setVerticalGroup(
            pnl_derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_derechoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_nombre_d)
                .addGap(18, 18, 18)
                .addComponent(lbl_nombre_d1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_resultadoCaudal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lbl_nombre_d2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_resultadoProfundidad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_nombre_d3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_resultadoAreaSuperf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_nombre_d4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_resultadoAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbl_nombre_d5)
                .addGap(18, 18, 18)
                .addComponent(lbl_resultadoLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_baseLayout = new javax.swing.GroupLayout(pnl_base);
        pnl_base.setLayout(pnl_baseLayout);
        pnl_baseLayout.setHorizontalGroup(
            pnl_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_baseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_izquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scr_centro, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_derecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_baseLayout.setVerticalGroup(
            pnl_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_baseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_derecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_izquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scr_centro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        Esencial01 e1 = new Esencial01();
        dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void cbx_personasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_personasActionPerformed

       // oper=cbx_personas.getSelectedItem().toString();







    }//GEN-LAST:event_cbx_personasActionPerformed

    private void txf_temperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_temperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_temperaturaActionPerformed

    private void rbn_material_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbn_material_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbn_material_1ActionPerformed

    private void cbx_imagen_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_imagen_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_imagen_c2ActionPerformed

    private void cbx_imagen_c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_imagen_c5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_imagen_c5ActionPerformed

    private void rbn_material_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbn_material_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbn_material_3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Esencial02_c1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Esencial02_c1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Esencial02_c1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Esencial02_c1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Esencial02_c1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbx_imagen_c1;
    private javax.swing.JCheckBox cbx_imagen_c2;
    private javax.swing.JCheckBox cbx_imagen_c3;
    private javax.swing.JCheckBox cbx_imagen_c4;
    private javax.swing.JCheckBox cbx_imagen_c5;
    private javax.swing.JCheckBox cbx_imagen_c6;
    private javax.swing.JComboBox<String> cbx_personas;
    private javax.swing.JLabel lbl_icono_i;
    private javax.swing.JLabel lbl_imagen_c1;
    private javax.swing.JLabel lbl_imagen_c2;
    private javax.swing.JLabel lbl_imagen_c3;
    private javax.swing.JLabel lbl_imagen_c4;
    private javax.swing.JLabel lbl_imagen_c5;
    private javax.swing.JLabel lbl_imagen_c6;
    private javax.swing.JLabel lbl_nombre_c1;
    private javax.swing.JLabel lbl_nombre_c2;
    private javax.swing.JLabel lbl_nombre_c3;
    private javax.swing.JLabel lbl_nombre_c3_1;
    private javax.swing.JLabel lbl_nombre_c3_2;
    private javax.swing.JLabel lbl_nombre_c4;
    private javax.swing.JLabel lbl_nombre_c5;
    private javax.swing.JLabel lbl_nombre_d;
    private javax.swing.JLabel lbl_nombre_d1;
    private javax.swing.JLabel lbl_nombre_d2;
    private javax.swing.JLabel lbl_nombre_d3;
    private javax.swing.JLabel lbl_nombre_d4;
    private javax.swing.JLabel lbl_nombre_d5;
    private javax.swing.JLabel lbl_nombre_i1;
    private javax.swing.JLabel lbl_nombre_i2;
    private javax.swing.JLabel lbl_resultadoAncho;
    private javax.swing.JLabel lbl_resultadoAreaSuperf;
    private javax.swing.JLabel lbl_resultadoCaudal;
    private javax.swing.JLabel lbl_resultadoLargo;
    private javax.swing.JLabel lbl_resultadoProfundidad;
    private javax.swing.JPanel pnl_base;
    private javax.swing.JPanel pnl_centro;
    private javax.swing.JPanel pnl_derecho;
    private javax.swing.JPanel pnl_imagenes1;
    private javax.swing.JPanel pnl_imagenes2;
    private javax.swing.JPanel pnl_izquierdo;
    private javax.swing.JRadioButton rbn_material_1;
    private javax.swing.JRadioButton rbn_material_2;
    private javax.swing.JRadioButton rbn_material_3;
    private javax.swing.JScrollPane scr_centro;
    private javax.swing.JTextArea txa_descripcion_i;
    private javax.swing.JTextField txf_temperatura;
    // End of variables declaration//GEN-END:variables
}
